name: 'firstdbtproject'
version: '1.0.0'
config-version: 2

# This must match the profile name in ~/.dbt/profiles.yml
profile: 'firstdbtproject'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  firstdbtproject:
    +materialized: view
